### PR TITLE
A clone of the old Apple official website - Built with HTML & CSS

### PR DESCRIPTION
**Pull request by idgm5**
I recreated the old Apple website following the instructions required by [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-backgrounds-and-gradients) and [Microverse Curriculum ](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/).

Any new changes will be documented and pushed on this pull request.

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @ghamtre , 👋

## You did a *great* job on this project! 💜 

- Good Readme template
- Good Pull Request Message

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have one warning. Please fix it.

- Check your stickler again and see if it's turned on and then commit to the branch to activate the checks. If you look at the checks section, it's empty.

- Improve your Readme file. You are using a great template, now fill it up with a more detailed description of the project.

- Your navbar is great, but the use of buttons is not the right one. You should use a normal anchor  `<a>` tag in those cases. See more info [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) and [here](https://stackoverflow.com/questions/21715162/when-should-i-use-a-button-button-or-a-link-a-in-html)

- Check the use of the background gradient on the original page. It is not on each nav element but in the whole navbar. Please change this and perhaps you will achieve a more similar effect to the original one.

- On the four images on the bottom, you used an onclick property. Please read this [link](https://stackoverflow.com/questions/5871640/why-is-using-onclick-in-html-a-bad-practice) to see why is not the best way to proceed.

- In the above case, you should be using anchor tags `<a>` to link the images to the proper destination, as the original page. Please implement this on your project.

- The original page has some hover styling that you are not replicating. Please include them in your project so it looks a closer clone.

- Change the font color of the footer links to match the original page.


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Use semantic HTML for the general structure of your projects. This includes a `<main>` tag for the main content of your body (excluding nav and footer)


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by idgm5** [comment]
@majovanilla The warning in HTML is a common issue because of the code of the icon I'm using for the search box inside of the placeholder.  https://teamtreehouse.com/community/-document-uses-the-unicode-private-use-areas

Stickler-ci is turned on. https://i.imgur.com/QSjKJmb.png

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Approved 🏆 🎈 

Hi @ghamtre, the project looks nice 👍 ,**Congratulations** on fixing all the recommended changes.Good luck with your next project 👍 

Happy coding_ 👨‍💻 
@slack on Daniel Larbi Addo

**Pull request merged**
